from __future__ import annotations

from typing import Any, Literal, Protocol


Json = dict[str, Any]
AdapterMode = Literal["fake", "disabled", "staging", "production"]

REQUIRED_CUSTOMER_SYNC_ADAPTER_RESULT_FIELDS = (
    "ok",
    "adapter",
    "mode",
    "operation",
    "idempotency_key",
    "target",
    "result",
    "audit_id",
    "side_effect_executed",
    "error_code",
    "error_message",
)


class ArchiveSyncAdapterContract(Protocol):
    def fetch_recent_messages(self, *, external_userid: str, limit: int = 20, sync_cursor: str = "", idempotency_key: str | None = None) -> Json: ...
    def fetch_incremental_archive_messages(self, *, sync_cursor: str = "", limit: int = 100, corp_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def normalize_archive_message(self, *, msgid: str = "", external_userid: str = "", payload: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def build_archive_sync_preview(self, *, external_userid: str = "", msgid: str = "", sync_cursor: str = "", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def record_archive_sync_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...


class ContactsSyncAdapterContract(Protocol):
    def fetch_external_contacts(self, *, follow_user_userid: str = "", sync_cursor: str = "", limit: int = 100, corp_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def fetch_contact_detail(self, *, external_userid: str, follow_user_userid: str = "", corp_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def fetch_follow_user_relations(self, *, external_userid: str = "", follow_user_userid: str = "", corp_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def build_contacts_sync_preview(self, *, external_userid: str = "", follow_user_userid: str = "", sync_cursor: str = "", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def record_contacts_sync_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...


class IdentityMappingAdapterContract(Protocol):
    def resolve_person_identity(self, *, external_userid: str = "", openid: str = "", unionid: str = "", mobile: str = "", person_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def upsert_identity_mapping(self, *, external_userid: str = "", openid: str = "", unionid: str = "", mobile: str = "", person_id: str = "", corp_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def link_openid_unionid_external_userid(self, *, external_userid: str, openid: str = "", unionid: str = "", corp_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def build_identity_mapping_preview(self, *, external_userid: str = "", openid: str = "", unionid: str = "", person_id: str = "", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def record_identity_mapping_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...


class CustomerProjectionSyncGatewayContract(Protocol):
    def update_customer_list_projection(self, *, projection_name: str = "customer_list", sync_cursor: str = "", external_userid: str = "", idempotency_key: str | None = None) -> Json: ...
    def update_customer_detail_projection(self, *, external_userid: str, projection_name: str = "customer_detail", idempotency_key: str | None = None) -> Json: ...
    def update_customer_timeline_projection(self, *, external_userid: str, projection_name: str = "customer_timeline", sync_cursor: str = "", idempotency_key: str | None = None) -> Json: ...
    def update_recent_messages_projection(self, *, external_userid: str, projection_name: str = "recent_messages", sync_cursor: str = "", idempotency_key: str | None = None) -> Json: ...
    def build_projection_sync_preview(self, *, projection_name: str, external_userid: str = "", sync_cursor: str = "", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def record_projection_sync_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...
