from __future__ import annotations

from typing import Any, Literal, Protocol


Json = dict[str, Any]
AdapterMode = Literal["fake", "disabled", "staging", "production"]

REQUIRED_MCP_OPENCLAW_RESULT_FIELDS = (
    "ok",
    "adapter",
    "mode",
    "operation",
    "idempotency_key",
    "target",
    "result",
    "audit_id",
    "side_effect_executed",
    "error_code",
    "error_message",
)


class McpToolGatewayContract(Protocol):
    def list_tools(self, *, request_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def invoke_tool(self, *, tool_name: str, arguments: dict[str, Any] | None = None, request_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def build_tool_preview(self, *, tool_name: str, arguments: dict[str, Any] | None = None, request_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def validate_tool_request(self, *, tool_name: str, arguments: dict[str, Any] | None = None, request_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def record_tool_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...


class CustomerContextToolAdapterContract(Protocol):
    def resolve_customer(self, *, external_userid: str = "", person_id: str = "", customer_ref: str = "", request_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def get_customer_context(self, *, external_userid: str, person_id: str = "", request_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def get_customer_timeline(self, *, external_userid: str, person_id: str = "", request_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def get_recent_messages(self, *, external_userid: str, person_id: str = "", request_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def build_customer_context_preview(self, *, external_userid: str = "", person_id: str = "", context_type: str = "", request_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def record_customer_context_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...


class OpenClawLegacyBridgeAdapterContract(Protocol):
    def build_openclaw_context_payload(self, *, member_id: str = "", external_userid: str = "", context_type: str = "", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def push_context_to_openclaw(self, *, member_id: str = "", external_userid: str = "", openclaw_context_id: str = "", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def resolve_legacy_skill_request(self, *, skill_name: str, request_id: str = "", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def build_legacy_bridge_preview(self, *, skill_name: str = "", context_type: str = "", request_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def record_openclaw_bridge_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...


class McpCompatibilityGatewayContract(Protocol):
    def map_legacy_tool_name(self, *, tool_name: str, request_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def map_legacy_payload(self, *, tool_name: str, payload: dict[str, Any] | None = None, request_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def normalize_tool_response(self, *, tool_name: str, response: dict[str, Any] | None = None, request_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def build_compatibility_preview(self, *, tool_name: str, request_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def record_compatibility_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...
