from __future__ import annotations

from typing import Any, Literal, Protocol


Json = dict[str, Any]
AdapterMode = Literal["fake", "disabled", "staging", "production"]

REQUIRED_PAYMENT_ADAPTER_RESULT_FIELDS = (
    "ok",
    "adapter",
    "mode",
    "operation",
    "idempotency_key",
    "target",
    "result",
    "audit_id",
    "side_effect_executed",
    "error_code",
    "error_message",
)


class ProductWriteGatewayContract(Protocol):
    def create_product(self, *, product_id: str = "", product_code: str = "", page_slug: str = "", amount: int = 0, currency: str = "CNY", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def update_product(self, *, product_id: str, product_code: str = "", page_slug: str = "", amount: int = 0, currency: str = "CNY", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def enable_product(self, *, product_id: str, product_code: str = "", page_slug: str = "", idempotency_key: str | None = None) -> Json: ...
    def disable_product(self, *, product_id: str, product_code: str = "", page_slug: str = "", idempotency_key: str | None = None) -> Json: ...
    def delete_product(self, *, product_id: str, product_code: str = "", page_slug: str = "", idempotency_key: str | None = None) -> Json: ...
    def build_product_write_preview(self, *, operation: str, product_id: str = "", product_code: str = "", page_slug: str = "", amount: int = 0, currency: str = "CNY", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def record_product_write_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...


class WeChatPayAdapterContract(Protocol):
    def create_jsapi_order(self, *, order_id: str, product_id: str = "", openid: str = "", amount: int = 0, currency: str = "CNY", return_url: str | None = None, idempotency_key: str | None = None) -> Json: ...
    def create_h5_order(self, *, order_id: str, product_id: str = "", amount: int = 0, currency: str = "CNY", return_url: str | None = None, idempotency_key: str | None = None) -> Json: ...
    def query_order(self, *, order_id: str = "", transaction_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def close_order(self, *, order_id: str, idempotency_key: str | None = None) -> Json: ...
    def verify_notify_signature(self, *, notify_id: str = "", provider_payload: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def parse_notify_payload(self, *, notify_id: str = "", provider_payload: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def build_checkout_preview(self, *, order_id: str, product_id: str = "", openid: str = "", amount: int = 0, currency: str = "CNY", return_url: str | None = None, idempotency_key: str | None = None) -> Json: ...


class AlipayAdapterContract(Protocol):
    def create_wap_order(self, *, order_id: str, product_id: str = "", payer_id: str = "", amount: int = 0, currency: str = "CNY", return_url: str | None = None, idempotency_key: str | None = None) -> Json: ...
    def query_order(self, *, order_id: str = "", transaction_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def close_order(self, *, order_id: str, idempotency_key: str | None = None) -> Json: ...
    def verify_notify_signature(self, *, notify_id: str = "", provider_payload: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def parse_notify_payload(self, *, notify_id: str = "", provider_payload: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def build_return_preview(self, *, order_id: str = "", transaction_id: str = "", status: str = "", provider_payload: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def build_checkout_preview(self, *, order_id: str, product_id: str = "", payer_id: str = "", amount: int = 0, currency: str = "CNY", return_url: str | None = None, idempotency_key: str | None = None) -> Json: ...


class PaymentNotifyGatewayContract(Protocol):
    def receive_wechat_notify(self, *, order_id: str = "", transaction_id: str = "", notify_id: str = "", amount: int = 0, currency: str = "CNY", provider_payload: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def receive_alipay_notify(self, *, order_id: str = "", transaction_id: str = "", notify_id: str = "", amount: int = 0, currency: str = "CNY", provider_payload: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def build_notify_preview(self, *, provider: str, order_id: str = "", transaction_id: str = "", notify_id: str = "", amount: int = 0, currency: str = "CNY", provider_payload: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def record_notify_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...
    def build_order_status_update_preview(self, *, provider: str, order_id: str = "", transaction_id: str = "", payment_status: str = "", idempotency_key: str | None = None) -> Json: ...


class PaymentReturnGatewayContract(Protocol):
    def receive_alipay_return(self, *, order_id: str = "", transaction_id: str = "", status: str = "", provider_payload: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def build_return_page_context(self, *, order_id: str = "", transaction_id: str = "", status: str = "", provider_payload: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def record_return_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...
