from __future__ import annotations

from typing import Any, Literal, Protocol


Json = dict[str, Any]
AdapterMode = Literal["fake", "disabled", "staging", "production"]

REQUIRED_QUESTIONNAIRE_ADAPTER_RESULT_FIELDS = (
    "ok",
    "adapter",
    "mode",
    "operation",
    "idempotency_key",
    "target",
    "result",
    "audit_id",
    "side_effect_executed",
    "error_code",
    "error_message",
)


class WeChatOAuthAdapterContract(Protocol):
    def build_authorize_url(self, *, slug: str | None = None, state: str | None = None, redirect: str | None = None, openid: str | None = None, unionid: str | None = None, external_userid: str | None = None, idempotency_key: str | None = None) -> Json: ...
    def exchange_code(self, *, code: str, state: str | None = None, redirect: str | None = None, idempotency_key: str | None = None) -> Json: ...
    def fetch_userinfo(self, *, openid: str, unionid: str | None = None, idempotency_key: str | None = None) -> Json: ...
    def resolve_oauth_identity(self, *, state: str | None = None, redirect: str | None = None, openid: str | None = None, unionid: str | None = None, external_userid: str | None = None, code: str | None = None, idempotency_key: str | None = None) -> Json: ...


class WeComTagAdapterContract(Protocol):
    def mark_external_contact_tags(self, *, external_userid: str, tag_ids: list[str], questionnaire_id: int | str | None = None, submission_id: str | None = None, idempotency_key: str | None = None) -> Json: ...
    def unmark_external_contact_tags(self, *, external_userid: str, tag_ids: list[str], questionnaire_id: int | str | None = None, submission_id: str | None = None, idempotency_key: str | None = None) -> Json: ...
    def validate_tag_ids(self, *, tag_ids: list[str], idempotency_key: str | None = None) -> Json: ...
    def build_tag_operation_preview(self, *, external_userid: str, tag_ids: list[str], operation: str = "mark", idempotency_key: str | None = None) -> Json: ...


class QuestionnaireExternalPushAdapterContract(Protocol):
    def push_submission_event(self, *, questionnaire_id: int | str, submission_id: str, webhook_url: str | None = None, payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def push_score_result_event(self, *, questionnaire_id: int | str, submission_id: str, score: int, webhook_url: str | None = None, payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def retry_push_event(self, *, event_id: str, webhook_url: str | None = None, idempotency_key: str | None = None) -> Json: ...
    def build_push_preview(self, *, questionnaire_id: int | str, webhook_url: str | None = None, payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...


class QuestionnaireSubmitSideEffectGatewayContract(Protocol):
    def apply_tags(self, *, questionnaire_id: int | str, submission_id: str, external_userid: str, tag_ids: list[str]) -> Json: ...
    def emit_external_push(self, *, questionnaire_id: int | str, submission_id: str, webhook_url: str | None, payload_summary: dict[str, Any]) -> Json: ...
    def emit_automation_questionnaire_result(self, *, questionnaire: dict[str, Any], submission: dict[str, Any], final_tags: list[str]) -> Json: ...
    def record_side_effect_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "") -> Json: ...
