from __future__ import annotations

from typing import Any, Literal, Protocol


Json = dict[str, Any]
AdapterMode = Literal["fake", "disabled", "staging", "production"]

REQUIRED_USER_OPS_ADAPTER_RESULT_FIELDS = (
    "ok",
    "adapter",
    "mode",
    "operation",
    "idempotency_key",
    "target",
    "result",
    "audit_id",
    "side_effect_executed",
    "error_code",
    "error_message",
)


class UserOpsDndWriteGatewayContract(Protocol):
    def enable_do_not_disturb(self, *, external_userid: str = "", mobile: str = "", owner_userid: str = "", record_id: str = "", reason_code: str = "", reason_text: str = "", operator: str = "", idempotency_key: str | None = None) -> Json: ...
    def cancel_do_not_disturb(self, *, external_userid: str = "", mobile: str = "", owner_userid: str = "", record_id: str = "", reason_code: str = "", reason_text: str = "", operator: str = "", idempotency_key: str | None = None) -> Json: ...
    def build_dnd_preview(self, *, action: str, external_userid: str = "", mobile: str = "", owner_userid: str = "", record_id: str = "", reason_code: str = "", reason_text: str = "", operator: str = "", idempotency_key: str | None = None) -> Json: ...
    def record_dnd_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...


class UserOpsBatchSendGatewayContract(Protocol):
    def build_batch_send_preview(self, *, batch_id: str = "", selection_mode: str = "", filters: dict[str, Any] | None = None, selected_ids: list[int] | None = None, excluded_ids: list[int] | None = None, content: str = "", targets: list[dict[str, Any]] | None = None, owner_buckets: list[dict[str, Any]] | None = None, include_do_not_disturb: bool = False, media_refs: list[dict[str, Any]] | None = None, idempotency_key: str | None = None) -> Json: ...
    def execute_batch_send(self, *, batch_id: str = "", record_id: str = "", content: str = "", targets: list[dict[str, Any]] | None = None, owner_buckets: list[dict[str, Any]] | None = None, operator: str = "", media_refs: list[dict[str, Any]] | None = None, idempotency_key: str | None = None) -> Json: ...
    def create_send_record(self, *, batch_id: str = "", record_id: str = "", payload: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def build_send_result_summary(self, *, batch_id: str = "", record_id: str = "", task_results: list[dict[str, Any]] | None = None, sent_count: int = 0, skipped_count: int = 0, idempotency_key: str | None = None) -> Json: ...


class WeComMessageDispatchAdapterContract(Protocol):
    def send_private_message(self, *, external_userid: str = "", external_userids: list[str] | None = None, owner_userid: str = "", mobile: str = "", record_id: str = "", batch_id: str = "", content: str = "", media_refs: list[dict[str, Any]] | None = None, idempotency_key: str | None = None) -> Json: ...
    def send_group_message(self, *, group_chat_id: str = "", owner_userid: str = "", record_id: str = "", batch_id: str = "", content: str = "", media_refs: list[dict[str, Any]] | None = None, idempotency_key: str | None = None) -> Json: ...
    def send_moment(self, *, owner_userid: str = "", record_id: str = "", batch_id: str = "", content: str = "", media_refs: list[dict[str, Any]] | None = None, idempotency_key: str | None = None) -> Json: ...
    def build_dispatch_preview(self, *, send_channel: str, target: dict[str, Any], content: str = "", media_refs: list[dict[str, Any]] | None = None, idempotency_key: str | None = None) -> Json: ...
    def resolve_dispatch_target(self, *, external_userid: str = "", mobile: str = "", owner_userid: str = "", record_id: str = "", batch_id: str = "", send_channel: str = "private", media_refs: list[dict[str, Any]] | None = None, idempotency_key: str | None = None) -> Json: ...
    def record_dispatch_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...


class UserOpsDeferredJobGatewayContract(Protocol):
    def enqueue_deferred_job(self, *, job_id: str = "", job_type: str = "", run_at: str = "", target: dict[str, Any] | None = None, payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def run_due_jobs(self, *, now: str = "", limit: int = 100, job_ids: list[str] | None = None, idempotency_key: str | None = None) -> Json: ...
    def build_deferred_job_preview(self, *, job_id: str = "", job_type: str = "", run_at: str = "", target: dict[str, Any] | None = None, payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def record_deferred_job_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...
