from __future__ import annotations

import re


RUNTIME_CONFIG_CUTOVER_KEYS_KEY = "AICRM_RUNTIME_CONFIG_CUTOVER_KEYS"

# These keys have moved from direct business-module environment access to the
# published runtime configuration boundary.  Until a key is explicitly added
# to RUNTIME_CONFIG_CUTOVER_KEYS_KEY, an existing environment value remains
# authoritative so the first deployment is behavior-preserving.
_FOUNDATION_RUNTIME_SETTING_KEYS = frozenset(
    {
        "ADMIN_LOGIN_REDIRECT_URI",
        "AICRM_ADMIN_AUTH_ENFORCED",
        "AICRM_ADMIN_SESSION_COOKIE_SECURE",
        "AICRM_AUTH_ARCHIVE_WORKER_CLIENT_ID",
        "AICRM_AUTH_ARCHIVE_WORKER_CLIENT_SECRET_REF",
        "AICRM_AUTH_AUTOMATION_WORKER_CLIENT_ID",
        "AICRM_AUTH_AUTOMATION_WORKER_CLIENT_SECRET_REF",
        "AICRM_AUTH_CALLBACK_WORKER_CLIENT_ID",
        "AICRM_AUTH_CALLBACK_WORKER_CLIENT_SECRET_REF",
        "AICRM_AUTH_CAMPAIGN_AGENT_CLIENT_ID",
        "AICRM_AUTH_CAMPAIGN_AGENT_CLIENT_SECRET_REF",
        "AICRM_AUTH_CA_FILE",
        "AICRM_AUTH_EXTERNAL_AGENT_CLIENT_ID",
        "AICRM_AUTH_EXTERNAL_AGENT_CLIENT_SECRET_REF",
        "AICRM_AUTH_GROUP_BROADCAST_CLIENT_ID",
        "AICRM_AUTH_GROUP_BROADCAST_CLIENT_SECRET_REF",
        "AICRM_AUTH_IDENTITY_CLIENT_ID",
        "AICRM_AUTH_IDENTITY_CLIENT_SECRET_REF",
        "AICRM_AUTH_ISSUER",
        "AICRM_AUTH_MCP_CLIENT_ID",
        "AICRM_AUTH_MCP_CLIENT_SECRET_REF",
        "AICRM_AUTH_OPS_REPORTER_CLIENT_ID",
        "AICRM_AUTH_OPS_REPORTER_CLIENT_SECRET_REF",
        "AICRM_INTERNAL_EVENTS_AI_CAMPAIGN_ENABLED",
        "AICRM_INTERNAL_EVENTS_ALLOWED_CONSUMERS",
        "AICRM_INTERNAL_EVENTS_ALLOWED_EVENT_CONSUMERS",
        "AICRM_INTERNAL_EVENTS_ALLOWED_EVENT_TYPES",
        "AICRM_INTERNAL_EVENTS_AUTO_EXECUTE",
        "AICRM_INTERNAL_EVENTS_AUTO_EXECUTE_MAX_BATCH_SIZE",
        "AICRM_INTERNAL_EVENTS_BROADCAST_TASK_ENABLED",
        "AICRM_INTERNAL_EVENTS_CUSTOMER_IDENTITY_ENABLED",
        "AICRM_INTERNAL_EVENTS_CUSTOMER_TAGS_ENABLED",
        "AICRM_INTERNAL_EVENTS_ENABLED",
        "AICRM_INTERNAL_EVENTS_LEGACY_PATH_MARKERS_ENABLED",
        "AICRM_INTERNAL_EVENTS_LEGACY_PATH_RETIRE_AFTER_DAYS",
        "AICRM_INTERNAL_EVENTS_OPS_PLAN_ENABLED",
        "AICRM_INTERNAL_EVENTS_OWNER_MIGRATION_ENABLED",
        "AICRM_INTERNAL_EVENTS_PAYMENT_ENABLED",
        "AICRM_INTERNAL_EVENTS_QUESTIONNAIRE_ENABLED",
        "AICRM_INTERNAL_EVENTS_SHADOW_ONLY",
        "AICRM_INTERNAL_EVENTS_WORKER_BATCH_SIZE",
        "AICRM_INTERNAL_EVENT_WORKER_BATCH_SIZE",
        "AICRM_NEXT_ALIPAY_MODE",
        "AICRM_NEXT_WECHAT_PAY_MODE",
        "AICRM_PII_AUDIT_ENABLED",
        "AICRM_ROUTE_POLICY_ENFORCED",
        "AICRM_WECOM_ADMIN_AUTH_ENABLE_REAL",
        "WECOM_AGENT_ID",
        "WECOM_CORP_ID",
        "WECOM_SECRET",
    }
)

# The integration gateway spans channel, engagement, automation, commerce,
# forms, AI, archive, and industry adapters.  The keys stay in one cutover set
# because the gateway is the single provider boundary that consumes them; each
# ConfigDefinition still declares the owning capability explicitly.
INTEGRATION_GATEWAY_RUNTIME_SETTING_KEYS = frozenset(
    {
        "AICRM_ENABLE_REAL_WECOM_GROUP_MESSAGE",
        "AICRM_ENABLE_REAL_WECOM_GROUP_SYNC",
        "AICRM_ENABLE_REAL_WECOM_PRIVATE_MESSAGE",
        "AICRM_HUANGYOUCAN_DB_CONNECT_TIMEOUT_SECONDS",
        "AICRM_HUANGYOUCAN_DB_HOST",
        "AICRM_HUANGYOUCAN_DB_NAME",
        "AICRM_HUANGYOUCAN_DB_PASSWORD",
        "AICRM_HUANGYOUCAN_DB_PORT",
        "AICRM_HUANGYOUCAN_DB_READ_TIMEOUT_SECONDS",
        "AICRM_HUANGYOUCAN_DB_USER",
        "AICRM_MEDIA_UPLOAD_CONFIG_REVIEWED",
        "AICRM_MEDIA_UPLOAD_LIVE_ADAPTER_ENABLED",
        "AICRM_MEDIA_UPLOAD_LIVE_UPLOAD_APPROVED",
        "AICRM_MEDIA_UPLOAD_PROVIDER_NAME",
        "AICRM_MEDIA_UPLOAD_PROVIDER_SECRET",
        "AICRM_NEXT_ALIPAY_MODE",
        "AICRM_NEXT_ARCHIVE_SYNC_MODE",
        "AICRM_NEXT_CONTACTS_SYNC_MODE",
        "AICRM_NEXT_CUSTOMER_CONTEXT_TOOL_MODE",
        "AICRM_NEXT_CUSTOMER_PROJECTION_SYNC_MODE",
        "AICRM_NEXT_ENABLE_REAL_ALIPAY",
        "AICRM_NEXT_ENABLE_REAL_ARCHIVE_SYNC",
        "AICRM_NEXT_ENABLE_REAL_CLOUD_STORAGE",
        "AICRM_NEXT_ENABLE_REAL_CONTACTS_SYNC",
        "AICRM_NEXT_ENABLE_REAL_CUSTOMER_PROJECTION_SYNC",
        "AICRM_NEXT_ENABLE_REAL_IDENTITY_MAPPING",
        "AICRM_NEXT_ENABLE_REAL_MCP_TOOLS",
        "AICRM_NEXT_ENABLE_REAL_OPENCLAW_BRIDGE",
        "AICRM_NEXT_ENABLE_REAL_PAYMENT_NOTIFY",
        "AICRM_NEXT_ENABLE_REAL_PRODUCT_WRITES",
        "AICRM_NEXT_ENABLE_REAL_QUESTIONNAIRE_WEBHOOK",
        "AICRM_NEXT_ENABLE_REAL_USER_OPS_BATCH_SEND",
        "AICRM_NEXT_ENABLE_REAL_USER_OPS_DEFERRED_JOBS",
        "AICRM_NEXT_ENABLE_REAL_USER_OPS_DND",
        "AICRM_NEXT_ENABLE_REAL_WECHAT_OAUTH",
        "AICRM_NEXT_ENABLE_REAL_WECHAT_PAY",
        "AICRM_NEXT_ENABLE_REAL_WECOM_DISPATCH",
        "AICRM_NEXT_ENABLE_REAL_WECOM_MEDIA",
        "AICRM_NEXT_ENABLE_REAL_WECOM_TAG",
        "AICRM_NEXT_IDENTITY_MAPPING_MODE",
        "AICRM_NEXT_MCP_TOOL_MODE",
        "AICRM_NEXT_MEDIA_STORAGE_MODE",
        "AICRM_NEXT_OPENCLAW_LEGACY_MODE",
        "AICRM_NEXT_PAYMENT_NOTIFY_MODE",
        "AICRM_NEXT_PRODUCT_WRITE_MODE",
        "AICRM_NEXT_QUESTIONNAIRE_WEBHOOK_MODE",
        "AICRM_NEXT_USER_OPS_BATCH_SEND_MODE",
        "AICRM_NEXT_USER_OPS_DEFERRED_JOBS_MODE",
        "AICRM_NEXT_USER_OPS_DND_MODE",
        "AICRM_NEXT_WECHAT_OAUTH_BASE_URL",
        "AICRM_NEXT_WECHAT_OAUTH_MODE",
        "AICRM_NEXT_WECHAT_OAUTH_TIMEOUT",
        "AICRM_NEXT_WECHAT_PAY_MODE",
        "AICRM_NEXT_WECOM_DISPATCH_MODE",
        "AICRM_NEXT_WECOM_MEDIA_MODE",
        "AICRM_NEXT_WECOM_TAG_MODE",
        "AICRM_OAUTH_IDENTITY_APP_ID",
        "AICRM_OAUTH_IDENTITY_APP_SECRET",
        "AICRM_OAUTH_IDENTITY_CONFIG_REVIEWED",
        "AICRM_OAUTH_IDENTITY_LIVE_ADAPTER_ENABLED",
        "AICRM_OAUTH_IDENTITY_LIVE_CALLBACK_APPROVED",
        "AICRM_OPENCLAW_MCP_AI_ASSIST_CONFIG_REVIEWED",
        "AICRM_OPENCLAW_MCP_AI_ASSIST_CREDENTIAL_SOURCE_REVIEWED",
        "AICRM_OPENCLAW_MCP_AI_ASSIST_ENDPOINT_REVIEWED",
        "AICRM_OPENCLAW_MCP_AI_ASSIST_LIVE_ADAPTER_ENABLED",
        "AICRM_OPENCLAW_MCP_AI_ASSIST_LIVE_CALL_APPROVED",
        "AICRM_OPENCLAW_MCP_AI_ASSIST_NO_AUTOMATION_EXECUTION_CONFIRMED",
        "AICRM_OPENCLAW_MCP_AI_ASSIST_NO_OUTBOUND_SEND_CONFIRMED",
        "AICRM_OPENCLAW_MCP_AI_ASSIST_PROMPT_REDACTION_CONFIRMED",
        "AICRM_PAYMENT_COMMERCE_LIVE_ADAPTER_ENABLED",
        "AICRM_PAYMENT_COMMERCE_LIVE_CALL_APPROVED",
        "AICRM_PAYMENT_COMMERCE_NO_MONEY_MOVEMENT_CONFIRMED",
        "AICRM_PAYMENT_COMMERCE_PROVIDER_CONFIG_REVIEWED",
        "AICRM_PAYMENT_COMMERCE_PROVIDER_NAME",
        "AICRM_PAYMENT_COMMERCE_PROVIDER_SECRET",
        "AICRM_PAYMENT_COMMERCE_SANDBOX_MODE_APPROVED",
        "AICRM_SIDEBAR_JSSDK_ADAPTER_MODE",
        "AICRM_SIDEBAR_JSSDK_REAL_ENABLED",
        "AICRM_SIDEBAR_JSSDK_SECRET",
        "AICRM_SIDEBAR_JSSDK_TIMEOUT_SECONDS",
        "AICRM_WECOM_ADMIN_AUTH_TIMEOUT",
        "AICRM_WECOM_CONTACT_CALLBACK_AES_KEY",
        "AICRM_WECOM_CONTACT_CALLBACK_CONFIG_REVIEWED",
        "AICRM_WECOM_CONTACT_CALLBACK_CORP_ID",
        "AICRM_WECOM_CONTACT_CALLBACK_LIVE_ADAPTER_ENABLED",
        "AICRM_WECOM_CONTACT_CALLBACK_LIVE_PROCESSING_APPROVED",
        "AICRM_WECOM_CONTACT_CALLBACK_TOKEN",
        "AICRM_WECOM_GROUP_ADAPTER_MODE",
        "AICRM_WECOM_GROUP_API_BASE",
        "AICRM_WECOM_GROUP_CORP_ID",
        "AICRM_WECOM_GROUP_SECRET",
        "AICRM_WECOM_GROUP_TIMEOUT",
        "AICRM_WECOM_MEDIA_API_BASE",
        "AICRM_WECOM_MEDIA_CORP_ID",
        "AICRM_WECOM_MEDIA_SECRET",
        "AICRM_WECOM_MEDIA_TIMEOUT",
        "AICRM_WECOM_OPERATION_MEMBERS_API_BASE",
        "AICRM_WECOM_OPERATION_MEMBERS_CORP_ID",
        "AICRM_WECOM_OPERATION_MEMBERS_SECRET",
        "AICRM_WECOM_OPERATION_MEMBERS_TIMEOUT",
        "AICRM_WECOM_PRIVATE_ADAPTER_MODE",
        "AICRM_WECOM_TAG_AGENT_SECRET",
        "AICRM_WECOM_TAG_API_BASE",
        "AICRM_WECOM_TAG_CORP_ID",
        "AICRM_WECOM_TAG_TIMEOUT_SECONDS",
        "WECHAT_MP_APP_ID",
        "WECHAT_MP_APP_SECRET",
        "WECHAT_MP_OAUTH_SCOPE",
        "WECHAT_OAUTH_TIMEOUT",
        "WECHAT_PAY_API_BASE",
        "WECHAT_PAY_API_V3_KEY",
        "WECHAT_PAY_APP_ID",
        "WECHAT_PAY_CERT_SERIAL_NO",
        "WECHAT_PAY_MCH_ID",
        "WECHAT_PAY_NOTIFY_URL",
        "WECHAT_PAY_PLATFORM_CERT_SERIAL_NO",
        "WECHAT_PAY_PLATFORM_PUBLIC_KEY_PATH",
        "WECHAT_PAY_PRIVATE_KEY_PATH",
        "WECHAT_PAY_TIMEOUT_SECONDS",
        "WECOM_AGENT_ID",
        "WECOM_API_BASE",
        "WECOM_ARCHIVE_TIMEOUT",
        "WECOM_AUTH_TIMEOUT",
        "WECOM_CONTACT_SECRET",
        "WECOM_CORP_ID",
        "WECOM_SECRET",
    }
)

BUSINESS_RUNTIME_SETTING_KEYS = frozenset(
    {
        "AICRM_AI_AUDIENCE_AGENT_FAKE_ALLOWED",
        "AICRM_AI_AUDIENCE_AGENT_FAKE_OUTPUT",
        "AICRM_AI_AUDIENCE_SPEC_ALLOWED_PREFIXES",
        "AICRM_AI_AUDIENCE_SPEC_ALLOW_NON_VERIFY_PREFIX",
        "AICRM_AI_AUDIENCE_SPEC_ALLOW_PUBLISH",
        "AICRM_RUNTIME_V2_AGENT_FAKE_ALLOWED",
        "AICRM_RUNTIME_V2_AGENT_FAKE_OUTPUT",
        "WECHAT_PAY_PENDING_ORDER_TTL_HOURS",
        "WECHAT_PAY_RECONCILIATION_PROPAGATION_SECONDS",
        "WECHAT_PAY_REFUND_NOTIFY_URL",
        "WECHAT_SHOP_API_BASE",
        "WECHAT_SHOP_APPID",
        "WECHAT_SHOP_HTTP_TIMEOUT_SECONDS",
    }
)

MANAGED_RUNTIME_SETTING_KEYS = frozenset(
    _FOUNDATION_RUNTIME_SETTING_KEYS
    | INTEGRATION_GATEWAY_RUNTIME_SETTING_KEYS
    | BUSINESS_RUNTIME_SETTING_KEYS
)

# A managed key may be observed through the compatibility resolver before it is
# safe to activate.  This explicit set is the publication allowlist and is also
# enforced by the all-business-code direct-environment CI scan.
CUTOVER_ELIGIBLE_RUNTIME_SETTING_KEYS = frozenset(MANAGED_RUNTIME_SETTING_KEYS)


def parse_runtime_config_cutover_keys(value: object) -> frozenset[str]:
    return frozenset(
        item.strip()
        for item in re.split(r"[,\s]+", str(value or ""))
        if item.strip()
    )


__all__ = [
    "BUSINESS_RUNTIME_SETTING_KEYS",
    "CUTOVER_ELIGIBLE_RUNTIME_SETTING_KEYS",
    "INTEGRATION_GATEWAY_RUNTIME_SETTING_KEYS",
    "MANAGED_RUNTIME_SETTING_KEYS",
    "RUNTIME_CONFIG_CUTOVER_KEYS_KEY",
    "parse_runtime_config_cutover_keys",
]
